import type { Metadata } from "next";
import { Inter } from 'next/font/google'

import { cn } from "@/lib/utils";

import { Toaster } from "@/components/ui/toaster";

import { Nav, NavLink } from "@/components/Nav";

import "./globals.css";

const inter = Inter({ subsets: ['latin'] })


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={cn(
          "min-h-screen bg-background font-sans antialiased",
          inter.className,
        )}
      >
        <Nav>
          <NavLink href="/">Home</NavLink>
          <NavLink href="/products">Products</NavLink>
          <NavLink href="/orders">My orders</NavLink>
        </Nav>
        <div className="container my-6 transition-all duration-500">
          {children}
        </div>
        <Toaster />
      </body>
    </html>
  );
}
